### ISSUE TITLE
script mdpow-pcw needed for calculating cyclohexane/water partition coefficient

### ISSUE THREAD

**Issue by iorga** [Becksteinlab/MDPOW#16]
The behavior should be similar with those of mdpow-pow. I have created an initial version by copying mdpow-pow and replacing `octanol` by `cyclohexane` and `oct` by `cyc` (Attention, we have Gcyclo.fep). Committed with SHA: 30ab593.

Currently it fails with the following error:
```
mdpow       : INFO     Analyzing directory '070'... (can take a while)
mdpow       : INFO     Reading water data '070/FEP/water/Ghyd.fep'
mdpow.fep   : INFO     Solvation free energy calculation for molecule UNK in solvent water.
mdpow.fep   : INFO     Base directory is '/gem/iorga/projects/sampl5_sims/070/070'
mdpow.fep   : INFO     Using setup directories under 'FEP/water': {'vdw': 'FEP/water/VDW', 'coulomb': 'FEP/water/Coulomb'}
mdpow.fep   : INFO     Default checkpoint file is '/gem/iorga/projects/sampl5_sims/070/070/FEP/water/Ghyd.fep'
mdpow       : INFO     Reading cyclohexane data '070/FEP/cyclohexane/Gcyc.fep'
mdpow       : CRITICAL Running analysis in directory '070' failed
mdpow       : ERROR    Catastrophic problem occurred, see the stack trace for hints.
Traceback (most recent call last):
  File "/home/chem/iorga/temp_ftp/mdpow-pcw", line 232, in <module>
    force=opts.force, stride=opts.stride, permissive=opts.permissive)
  File "/home/chem/iorga/temp_ftp/mdpow-pcw", line 99, in run_pcw
    gwat, gcyc = load_gsolv(directory, permissive=kwargs.pop('permissive',False),)
  File "/home/chem/iorga/temp_ftp/mdpow-pcw", line 60, in load_gsolv
    gcyc = mdpow.fep.Gcyc(filename=files['cyclohexane'], basedir=directory, permissive=permissive)
AttributeError: 'module' object has no attribute 'Gcyc'
```

**Comment by orbeckst** [comment]
Was about to do something similar, Will have a look.

Note that you should add your icsn.cnrs-gif.fr email to your GitHub account so that GitHun can identify @iorga as the author of the commit.

**Comment by iorga** [comment]
I've just added the email address, thanks @orbeckst.
