### ISSUE TITLE
mdpow-solvation fails for benzene example

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#184]
I am running the benzene example and now want to analyze the data:

```
(mdpow38) TCLAPHY-C02DF1NWML87:TRIAL oliver$ mdpow-solvationenergy --solvent water benzene
mdpow       : INFO     MDPOW 0.7.0+3.g639c16f.dirty starting.
mdpow       : INFO     Copyright (c) 2010-2021 Shujie Fan, Ian Kenney, Alia Lescoulie, Bogdan Iorga, and Oliver Beckstein
mdpow       : INFO     Released under the GNU Public Licence, version 3.
mdpow       : INFO     For bug reports and help: https://github.com/Becksteinlab/MDPOW/issues
mdpow.config: INFO     Using the bundled force fields from GMXLIB='~/Projects/Methods/MDPOW/mdpow/top'.
mdpow.config: INFO     If required, override this behaviour by setting the environment variable GMXLIB yourself.
mdpow       : INFO     Analyzing directory 'benzene'... (can take a while)
mdpow       : INFO     [benzene] Reading water data 'benzene/FEP/water/Ghyd.fep'
mdpow.fep   : INFO     Solvation free energy calculation for molecule BNZ in solvent water.
mdpow.fep   : INFO     Base directory is '~/Projects/Methods/MDPOW/doc/examples/TRIAL/benzene'
mdpow.fep   : INFO     Using setup directories under 'FEP/water': {'coulomb': 'FEP/water/Coulomb', 'vdw': 'FEP/water/VDW'}
mdpow.fep   : INFO     Default checkpoint file is '~/Projects/Methods/MDPOW/doc/examples/TRIAL/benzene/FEP/water/Ghyd.fep'
mdpow       : INFO     The solvent is water.
mdpow       : CRITICAL Running analysis in directory 'benzene' failed
mdpow       : ERROR    Catastrophic problem occurred, see the stack trace for hints.
Traceback (most recent call last):
  File "~/anaconda3/envs/mdpow38/lib/python3.8/site-packages/gromacs/utilities.py", line 122, in __getattribute__
    return super(AttributeDict,self).__getattribute__(x)
AttributeError: 'AttributeDict' object has no attribute 'Gibbs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Projects/Methods/MDPOW/scripts/mdpow-solvationenergy", line 291, in <module>
    run_gsolv(opts.solvent, directory, plotfile=plotfile,
  File "~/Projects/Methods/MDPOW/scripts/mdpow-solvationenergy", line 135, in run_gsolv
    if kwargs['force'] or (not hasattr(gsolv.results.DeltaA, 'Gibbs')):
  File "~/anaconda3/envs/mdpow38/lib/python3.8/site-packages/gromacs/utilities.py", line 124, in __getattribute__
    return self[x]
KeyError: 'Gibbs'
Traceback (most recent call last):
  File "~/anaconda3/envs/mdpow38/lib/python3.8/site-packages/gromacs/utilities.py", line 122, in __getattribute__
    return super(AttributeDict,self).__getattribute__(x)
AttributeError: 'AttributeDict' object has no attribute 'Gibbs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/anaconda3/envs/mdpow38/bin/mdpow-solvationenergy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "~/Projects/Methods/MDPOW/scripts/mdpow-solvationenergy", line 291, in <module>
    run_gsolv(opts.solvent, directory, plotfile=plotfile,
  File "~/Projects/Methods/MDPOW/scripts/mdpow-solvationenergy", line 135, in run_gsolv
    if kwargs['force'] or (not hasattr(gsolv.results.DeltaA, 'Gibbs')):
  File "~/anaconda3/envs/mdpow38/lib/python3.8/site-packages/gromacs/utilities.py", line 124, in __getattribute__
    return self[x]
KeyError: 'Gibbs'
```

**Comment by orbeckst** [comment]
This bug is due to GromacsWrapper#210.

I'll add a workaround in MDPOW for now.
