### ISSUE TITLE
Use AutoMBAR instead of MBAR 

### ISSUE THREAD

**Issue by VOD555** [Becksteinlab/MDPOW#233]
The MBAR estimator in alchemlyb 1.X (pymbar 3.X) may not converge correctly.
see https://github.com/choderalab/pymbar/issues/419

We'll use AutoMBAR instead of MBAR to avoid this error.

**Comment by iorga** [comment]
Thanks @VOD555 . I made the update, but now I have the following error. Can you please have a look?
```
(/sge/packs/anaconda3_centos6_envs/mdpow_py3) mdpow-solvationenergy -S water --estimator alchemlyb S16
mdpow       : INFO     MDPOW 0.8.0+13.g729a6fb.dirty starting.
mdpow       : INFO     Copyright (c) 2010-2021 Shujie Fan, Ian Kenney, Alia Lescoulie, Bogdan Iorga, and Oliver Beckstein
mdpow       : INFO     Released under the GNU Public Licence, version 3.
mdpow       : INFO     For bug reports and help: https://github.com/Becksteinlab/MDPOW/issues
Traceback (most recent call last):
  File "/sge/packs/anaconda3_centos6_envs/mdpow_py3/bin/mdpow-solvationenergy", line 4, in <module>
    __import__('pkg_resources').run_script('MDPOW==0.8.0+13.g729a6fb.dirty', 'mdpow-solvationenergy')
  File "/sge/packs/anaconda3_centos6_envs/mdpow_py3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/sge/packs/anaconda3_centos6_envs/mdpow_py3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/sge/packs/anaconda3_centos6_envs/mdpow_py3/lib/python3.9/site-packages/MDPOW-0.8.0+13.g729a6fb.dirty-py3.9.egg/EGG-INFO/scripts/mdpow-solvationenergy", line 51, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/sge/packs/anaconda3_centos6_envs/mdpow_py3/lib/python3.9/site-packages/MDPOW-0.8.0+13.g729a6fb.dirty-py3.9.egg/mdpow/fep.py", line 161, in <module>
ImportError: cannot import name 'AutoMBAR' from 'alchemlyb.estimators' (/sge/packs/anaconda3_centos6_envs/mdpow_py3/lib/python3.9/site-packages/alchemlyb/estimators/__init__.py)
```

**Comment by VOD555** [comment]
@iorga What's the version of alchemlyb that you are using?

**Comment by iorga** [comment]
@VOD555 I had alchemlyb 0.5.1. Updating it to 1.0.1 solved the issue. Many thanks.

With this new version I could analyze correctly the sims GAFF/S16, which couldn't converge before.
